language: java

jdk:
  - oraclejdk11

matrix:
  - jdk: oraclejdk11
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

script:
  - mvn -Pstatic-analysis
  - mvn -Parchitecture-tests
  - mvn -Punit-tests
  - mvn -Pruntime-analysis
